apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: grafana-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: elimrani.z@gmail.com
    privateKeySecretRef:
      name: grafana-cluster-issuer-key
    solvers:
    - http01:
       ingress:
         class: nginx