apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-app
  namespace: default
spec:
  dnsNames:
    - auth.grow-as-team.com
  secretName: auth-app-tls
  issuerRef:
    name: auth-cluster-issuer
    kind: ClusterIssuer