name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the Docker image
      run: docker build --file MicroServices/AuthService/Auth.API/Dockerfile --tag zaydimr/staffing-auth-service MicroServices
      
    - name : Push to Docker Hub
      run: docker push zaydimr/staffing-auth-service
