name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build AuthService image
        run: docker build --file MicroServices/AuthService/Auth.API/Dockerfile --tag zaydimr/staffing-auth-service MicroServices
  
      - name: Build WeatherService image
        run: docker build --file MicroServices/Weather/Dockerfile --tag zaydimr/staffing-weather-service MicroServices
        
      - name : Push images to Docker Hub
        run: |
          docker push zaydimr/staffing-auth-service
          docker push zaydimr/staffing-weather-service

  Kubernetes-Deploy:
    runs-on: self-hosted
    needs: Docker-Build-Push
    steps:       
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Re-deploy microservices
        run:  |
          kubectl delete -R -f .\K8S\microservices\
          kubectl apply -R -f .\K8S\microservices\
  
      - name: Re-configure LoadBalancer
        run: kubectl apply -R -f .\K8S\global-ingress.yaml
